# Dockerfile.mysql
FROM mysql:8.0

# Инициализация базы и пользователя
ENV MYSQL_DATABASE=app_db \
    MYSQL_USER=app_user \
    MYSQL_PASSWORD=1234 \
    MYSQL_ROOT_PASSWORD=rootpass

EXPOSE 3306
CMD ["mysqld"]